#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-trio
Version  : 0.22.1
Release  : 13
URL      : https://files.pythonhosted.org/packages/81/e5/9277865340bf4abb74e4d40eea736d7adeb92f0c0529281f7bd702c590e1/trio-0.22.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/81/e5/9277865340bf4abb74e4d40eea736d7adeb92f0c0529281f7bd702c590e1/trio-0.22.1.tar.gz
Summary  : A friendly Python library for async concurrency and I/O
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: pypi-trio-license = %{version}-%{release}
Requires: pypi-trio-python = %{version}-%{release}
Requires: pypi-trio-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
.. image:: https://img.shields.io/badge/chat-join%20now-blue.svg
:target: https://gitter.im/python-trio/general
:alt: Join chatroom

%package license
Summary: license components for the pypi-trio package.
Group: Default

%description license
license components for the pypi-trio package.


%package python
Summary: python components for the pypi-trio package.
Group: Default
Requires: pypi-trio-python3 = %{version}-%{release}

%description python
python components for the pypi-trio package.


%package python3
Summary: python3 components for the pypi-trio package.
Group: Default
Requires: python3-core
Provides: pypi(trio)
Requires: pypi(attrs)
Requires: pypi(idna)
Requires: pypi(outcome)
Requires: pypi(sniffio)
Requires: pypi(sortedcontainers)

%description python3
python3 components for the pypi-trio package.


%prep
%setup -q -n trio-0.22.1
cd %{_builddir}/trio-0.22.1
pushd ..
cp -a trio-0.22.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1688412673
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-trio
cp %{_builddir}/trio-%{version}/LICENSE.APACHE2 %{buildroot}/usr/share/package-licenses/pypi-trio/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/trio-%{version}/LICENSE.MIT %{buildroot}/usr/share/package-licenses/pypi-trio/078fcfe40c1993810743750c91b85e5e5022b28c || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-trio/078fcfe40c1993810743750c91b85e5e5022b28c
/usr/share/package-licenses/pypi-trio/2b8b815229aa8a61e483fb4ba0588b8b6c491890

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
